version: '3'

services:
  db:
    env_file:
      - .env
    ports:
      - "5432:5432"

  etl_service:
    env_file:
      - .env

  elastic:
    ports:
      - "9200:9200"

  cache:
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  service:
    env_file:
      - .env
    entrypoint: >
      sh -c "./start.sh"
    ports:
      - "8001:8000"

  nginx:
     ports:
       - "80:80"

volumes:
  postgres_data:

