version: '3.5'

services:
  ugc-clickhouse-zookeeper:
    image: zookeeper:3.5
    container_name: ugc-clickhouse-zookeeper
    hostname: ugc-clickhouse-zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - ucg_clickhouse_network

  clickhouse-node1:
    image: yandex/clickhouse-server
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./ch_config/node1:/etc/clickhouse-server
    depends_on:
      - ugc-clickhouse-zookeeper
    networks:
      - ucg_clickhouse_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-node2:
    image: yandex/clickhouse-server
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./ch_config/node2:/etc/clickhouse-server
    depends_on:
      - ugc-clickhouse-zookeeper
    networks:
      - ucg_clickhouse_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-node3:
    image: yandex/clickhouse-server
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./ch_config/node3:/etc/clickhouse-server
    depends_on:
      - ugc-clickhouse-zookeeper
    networks:
      - ucg_clickhouse_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-node4:
    image: yandex/clickhouse-server
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./ch_config/node4:/etc/clickhouse-server
    depends_on:
      - ugc-clickhouse-zookeeper
    networks:
      - ucg_clickhouse_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-init:
    build: ./clickhouse-init
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./data/sql:/sql
    depends_on:
      clickhouse-node1:
        condition: service_healthy
      clickhouse-node2:
        condition: service_healthy
      clickhouse-node3:
        condition: service_healthy
      clickhouse-node4:
        condition: service_healthy
    networks:
      - ucg_clickhouse_network


networks:
  ucg_clickhouse_network:
    driver: bridge
