version: '3.5'

services:
  clickhouse-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - "2182:2182"
      
  clickhouse-node1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./data/node2:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./data/node3:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper

  clickhouse-node4:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./data/node4:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper

  clickhouse-init:
    build:
      context: ./clickhouse-init
      dockerfile: Dockerfile
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./data/sql:/sql
    depends_on:
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4