filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  loadbalance: true
  hosts: ["logstash:5045"]