# Generated by Django 3.2 on 2023-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('certificate', models.CharField(blank=True, max_length=512, null=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True, unique=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'film_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'genre_film_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_film_work',
                'managed': False,
            },
        ),
    ]
