version: '3'
services:
  db:
    image: postgres:13
    restart: on-failure
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data/
    networks:
      - app_network
    ports:
      - "5432:5432"
    expose:
      - "5432"

  service:
    build: .
    env_file:
      - ./.env
    networks:
      - app_network
    expose:
      - "8000"
    ports:
      - "8080:8000"
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
#    depends_on:
#      - service
#    ports:
#      - "80:80"
