version: '3'

services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cinema

  ugc_api:
    build: ./api_ugc
    image: ugc_image:latest
    container_name: ugc_api
    restart: always
    entrypoint: >
      sh -c "./start.sh"
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ugc/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cinema

networks:
  cinema:
    external: true
