@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.5.0/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title [Component] Online Cinema System - UGC App

Person(user, "Customer", "A customer of the Online Cinema with personal account")
Container_Boundary(c1, "UGC Application") {
    Component(fastapi, "FastAPI", "Python", "Allows users to provide feedback, etc")
    Component(etl, "ETL Service", "Python", "Provides functionality related to exporting data from one storage, its transformation and loading into another")
    ComponentDb(kafka, "OLTP Storage", "Kafka", "Stores information about film watching progress, etc")
    ComponentDb(storage, "OLAP Storage", "Clickhouse", "Stores information about users activity")
}
ContainerDb(movie_db, "Movie Storages", "", "Stores all information about movies content, searching, etc.")
Container(auth, "AUTH App", "", "Provides authorization functionality via a JSON/HTTPS API")

Rel(user, fastapi, "Makes API calls to", "JSON/HTTPS")

Rel(fastapi, kafka, "Produces events to")
Rel_L(etl, kafka, "Read from")
Rel_R(etl, storage, "Writes to")

Rel_R(fastapi, movie_db, "Reads from", "SQL/TCP")
Rel(fastapi, auth, "Request to access", "JSON/HTTPS")

SHOW_FLOATING_LEGEND()

@enduml
