version: '3.5'

services:
  ########################
  ###  Kafka Services  ###
  ########################
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - cinema

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "host.docker.internal:9092"]
      interval: 30s
      timeout: 30s
      retries: 4
    networks:
      - cinema

  ########################
  ###    Events API    ###
  ########################
  events_api:
    build: ./api_events
    image: events_api-image
    container_name: events
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - zoo1
      - kafka1
    networks:
      - cinema

  ########################
  ###      ETL         ###
  ########################
  clickhouse-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - "2182:2182"
    networks:
      - cinema

  etl-app:
    container_name: etl-app
    build:
      context: ./etl/src
      dockerfile: Dockerfile
    image: etl-app:1.0.0
    restart: always
    networks:
      - cinema

  clickhouse-node1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./etl/data/node1:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper
    networks:
      - cinema

  clickhouse-node2:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./etl/data/node2:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper
    networks:
      - cinema

  clickhouse-node3:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./etl/data/node3:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper
    networks:
      - cinema

  clickhouse-node4:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./etl/data/node4:/etc/clickhouse-server
    depends_on:
      - clickhouse-zookeeper
    networks:
      - cinema

  clickhouse-init:
    build:
      context: ./etl/clickhouse-init
      dockerfile: Dockerfile
    environment:
      DEFAULT_USER_PASSWORD: test
      ADMIN_PASSWORD: test
    volumes:
      - ./etl/data/sql:/sql
    depends_on:
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
    networks:
      - cinema


networks:
  cinema: