name: Linter Check on Push
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.x
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0
    - name: Run Flake8
      run: flake8 .


  content_api_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Recreate .env
      run: |
        echo "${{ secrets.DOTENV_CONTENT }}" > .env

    - name: Running tests
      run: cd content-service/content_api/tests/functional && bash run_tests.sh


  ugc_api_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Recreate .env
      run: |
        echo "${{ secrets.DOTENV_CONTENT }}" > .env

    - name: Running tests
      run: cd ugc-service/api_ugc/tests && bash run_tests.sh